name: mycroft-core
version: 18.8.0
summary:  79 char long summary
description:  a longer description for the snap
confinement: devmode # use "strict" to enforce system access only via declared interfaces
build-packages: [python-dev, python-virtualenv, python-setuptools, python-gobject-2-dev, virtualenvwrapper, libpcre2-dev, libtool, libffi-dev, libssl-dev, autoconf, bison, swig, libglib2.0-dev, portaudio19-dev, mpg123, python-psutil, speech-dispatcher]
parts:
  mimic:
    plugin: autotools
    configflags:
      - --enable-static=no
      - --prefix=/usr/local/
      - --with-audio=pulseaudio
    source: https://github.com/MycroftAI/mimic.git
    source-type: git
    build-packages:
      - libpulse-dev
      - libltdl-dev
      - gcc
      - make
      - pkg-config
      - libasound2-dev
    stage-packages: [libpulse0]
    prime:
      - usr/local/bin
      - usr/local/include
      - usr/local/lib

  mycroft-core:
    plugin: python
    source: https://github.com/MycroftAI/mycroft-core.git
    source-type: git
    source-branch: dev
    build-packages: [python-psutil, python-setuptools]
    stage-packages: [speech-dispatcher]

apps:
  mimic:
    command: usr/local/bin/mimic
    plugs: [pulseaudio]
  messagebus:
    plugs: [home, network, network-bind]
    command: usr/bin/mycroft-messagebus
    daemon: simple
  skills-client:
    plugs: [home]
    command: usr/bin/mycroft-skills
    daemon: simple
  speech-client:
    plugs: [home, network, pulseaudio]
    command: usr/bin/mycroft-speech-client
    daemon: simple
  cli-client:
    command: usr/bin/mycroft-cli-client
